/* eslint-disable @next/next/no-img-element */
import React from "react";
import { useEffect } from "react";
import Head from "next/head";
import Layout from "../src/components/Layout/Layout";

// Types
import type { NextPage } from "next";

// MUI Components
import Box from "@mui/material/Box";
import CharactersList from "../src/components/CharacterList/CharactersList";

// Redux Hooks
import { useAppSelector, useAppDispatch } from "../src/hooks/hooks";

// Redux Store
import { store } from "../src/store/store";

import {
  getRickAndMortyCharacters,
  selectFilteredRickAndMortyCharacters,
  selectName,
} from "../src/store/slices/rickAndMortySlice";


const Home: NextPage = () => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    // if store is not null then dispatch getRickAndMortyCharacters
    if (store) {
      dispatch(getRickAndMortyCharacters({}));
    }
  }, []);

  const rickAndMortyCharacters = useAppSelector(
    selectFilteredRickAndMortyCharacters
  );
  const search = useAppSelector(selectName);

  return (
    <Layout isDetailPage={false}>
      <Head>
        <title>Rick And Morty Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          my: 4,
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <CharactersList characters={rickAndMortyCharacters} />
      </Box>
    </Layout>
  );
};

export default Home;
