import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import * as React from "react";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import CharacterCard from "../src/components/ui/CharacterCard";
import MyPagination from "../src/components/ui/MyPagination";
import SideBar from "../src/components/ui/Sidebar";
import NavBar from "../src/components/ui/NavBar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rick & Morty Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar>
        <CharacterCard />
        <MyPagination />
        <SideBar />
      </NavBar>
    </>
  );
};

export default Home;
